name: Rust Versioning

on:
  pull_request:
    branches: [ master ]
    types: [ labeled, unlabeled, opened, synchronize, closed, reopened ]

env:
  CARGO_TERM_COLOR: always

jobs:
  verify-version-label:
    name: Verify version label
    runs-on: ubuntu-latest
    steps:
    - name: Check if patch increment
      if: ${{ contains(github.event.pull_request.labels.*.name, 'patch-increment') }}
      run: |
        echo "RUST_VERSION_INCREMENT=patch" >> $GITHUB_ENV
    - name: Check if minor increment
      if: ${{ contains(github.event.pull_request.labels.*.name, 'minor-increment') }}
      run: |
        echo "RUST_VERSION_INCREMENT=minor" >> $GITHUB_ENV
    - name: Check if major increment
      if: ${{ contains(github.event.pull_request.labels.*.name, 'major-increment') }}
      run: |
        echo "RUST_VERSION_INCREMENT=major" >> $GITHUB_ENV
    - name: Fail if no version label exist
      if: ${{ env.RUST_VERSION_INCREMENT == '' }}
      run: |
        echo "No version increment label set"
        exit 1


  apply-version:
    if: ${{ github.event.action == 'closed' && github.event.pull_request.merged == true }}
    name: Apply version label
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout PR
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh pr checkout ${{ github.event.pull_request.number }}
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: cargo-bump
    - name: Install cargo-bump
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: cargo-bump
    - name: Increase major version
      if: ${{ contains(github.event.pull_request.labels.*.name, 'major-increment') }}
      uses: actions-rs/cargo@v1
      with:
        command: bump
        args: major
    - name: Increase minor version
      if: ${{ contains(github.event.pull_request.labels.*.name, 'minor-increment') }}
      uses: actions-rs/cargo@v1
      with:
        command: bump
        args: minor
    - name: Increase patch version
      if: ${{ contains(github.event.pull_request.labels.*.name, 'patch-increment') }}
      uses: actions-rs/cargo@v1
      with:
        command: bump
        args: patch
    - name: Create new version
      run: |
        git config --global user.email '<>'
        git config --global user.name "Gitlab CI"
        git commit Cargo.toml -m "Bump version"
    - name: Push new version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: git push
